In [250]:
import numpy as np

In [252]:
kanto = np.array([73,67,43])

In [254]:
print(kanto)

[73 67 43]


In [256]:
weights=np.array([0.3,0.2,0.5])

In [258]:
type(kanto)

numpy.ndarray

In [260]:
type(weights)

numpy.ndarray

In [262]:
weights[0]

0.3

In [264]:
#dot product
np.dot(kanto,weights)

56.8

In [266]:
(kanto*weights).sum()

56.8

In [268]:
#multi-dimensional array
climate_data = np.array([[73,67,43],
                        [91,88,64],
                        [87,134,58],
                        [102,43,37],
                        [69,96,70]])

In [270]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [272]:
#2D
climate_data.shape

(5, 3)

In [274]:
#1D
weights.shape

(3,)

In [276]:
climate_data.dtype

dtype('int32')

In [278]:
#matrix multiplication
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [280]:
#'@' is matrix multiplication
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [282]:
import urllib.request
urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x1acf9d5c510>)

In [283]:
#to read this file into numpy array,use 'genfromtxt' function
climate_data = np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [284]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [285]:
yields = climate_data @ weights

In [286]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [287]:
climate_results = np.concatenate((climate_data, yields.reshape(10000,1)), axis=1)

In [288]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [289]:
np.savetxt('climate_results.txt',
           climate_results,
          fmt='%2f',
          header='temperature,rainfall, humidity, yeild_apples')

In [338]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [291]:
arr3.shape

(3, 2, 4)

In [292]:
arr3[1,1,2]

36.0

In [293]:
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [342]:
#Mixing indices and ranges
arr3[:,1,:3]

array([[13. , 14. , 15. ],
       [63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [307]:
#Using fewer indices
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [309]:
arr3[:2,1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [312]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [314]:
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [316]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [318]:
np.random.rand(5)

array([0.82285966, 0.45198259, 0.17377108, 0.17287513, 0.63141593])

In [320]:
np.random.randn(2,3)

array([[ 0.7374565 ,  1.02046774, -1.03260522],
       [ 0.72146248, -0.88440049, -0.41528067]])

In [322]:
#Fixed value
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [324]:
#Range with start,end and step
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [336]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])